name: JSDoc Generation

on:
  push:
    branches:
      - main

jobs:  
  jsdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push back
          ref: main

      - name: Install modules
        run: npm install

      - name: Run JSDoc
        run: npx jsdoc ./js -r -d ./docs/jsdoc

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -B jsdoc/generate-docs

          git add docs/jsdoc
          git commit -m "Update JSDoc documentation" || echo "No changes"

          git push -f --set-upstream origin jsdoc/generate-docs

      - name: Create Pull request
        uses: diillson/auto-pull-request@v1.0.1
        with:
          source_branch: "jsdoc/generate-docs"
          destination_branch: "main"
          pr_title: "Automatic Documentation Update"
          pr_body: | 
            :crown: *An automated PR to update docs*
