name: JSDoc Generation

on:
  push:
    branches:
      - main

jobs:  
  jsdoc:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # needed to push back
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Install modules
        run: npm install

      - name: Run JSDoc
        run: npx jsdoc ./js -r -d ./docs/jsdoc

      - name: Commit and push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git checkout -b jsdoc/generate-docs

          git add docs/jsdoc
          git commit -m "Update JSDoc documentation" || echo "No changes"

          git push --force --set-upstream origin jsdoc/generate-docs

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: jsdoc/generate-docs
          title: "Update JSDoc Documentation"
          body: |
            This pull request updates the generated JSDoc documentation.
            It was automatically created by a GitHub Action.
          base: main

