name: CI # name of the test

on: [push, pull_request] # the Github Action will activate "on" the event that you "push" to the repo

jobs: # the things being executed
  tests: # the name of your status check, will become important when you do branch protection
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
      - uses: actions/checkout@v4 # using version 4 of Actions
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm test ./__tests__/dummy-test.js # the actual testing line
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint ./

  validate-html:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
  
        - name: Validate markup with Nu HTML Checker
          uses: Cyb3r-Jak3/html5validator-action@v7.2.0   
          with:
            root: .               
            format: github        
            css: true  
            blacklist: "node_modules" 
