name: CI 

on:
  push:
    branches:
      - main # only run on direct pushes to main
  pull_request:
    # run on all PRs

jobs:
  tests: 
    runs-on: ubuntu-latest 
    permissions:          # added: token so Quality Monitor can comment
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Unit Test with coverage      # changed: enable coverage output
        run: npm test -- --coverage
      - name: Convert LCOV → Cobertura     
        run: npx lcov-to-cobertura-xml \ 
             -i coverage/lcov.info \
             -o coverage/cobertura-coverage.xml
      - name: Find pull-request number   
        if: github.event_name == 'pull_request'
        id: pr
        uses: jwalton/gh-find-current-pr@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Quality Monitor summary      # added: aggregate & comment
        if: github.event_name == 'pull_request'
        uses: uhafner/quality-monitor@v1
        with:
          pr-number:    ${{ steps.pr.outputs.number }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
    
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint ./
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 
      - name: Validate markup with Nu HTML Checker
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0   
        with:
          root: .               
          format: gnu        
          css: true  
          blacklist: "node_modules"
  jsdoc:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run JSDoc
      run: npx jsdoc ./js -r -d ./docs/jsdoc
    - name: Commit generated docs
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add docs/jsdoc
        git commit -m "Update JSDoc documentation [skip ci]" || echo "No changes to commit"
        git push