name: CI 

on:
  push:
    branches:
      - main # only run on direct pushes to main
  pull_request:
    # run on all PRs

jobs: 
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm run test  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint ./
  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate markup with Nu HTML Checker
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0   
        with:
          root: .               
          format: gnu        
          css: true  
          blacklist: "node_modules"
  jsdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.1

  # monitor-project-quality:
  #   name: Run the quality monitor
  #   runs-on: ubuntu-latest

  #   permissions:        
  #     contents: read
  #     pull-requests: write  

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Build (compile, test, mutation coverage, static analysis)
  #       run: mvn -ntp clean verify -Ppit

  #     - name: Find current pull-request number
  #       id: pr
  #       uses: jwalton/gh-find-current-pr@v1
  #       with:
  #         github-token: ${{ secrets.GITHUB_TOKEN }}   # ← add token here too (optional but recommended)

  #     - name: Run Quality Monitor
  #       uses: uhafner/quality-monitor@v1
  #       with:
  #         pr-number:    ${{ steps.pr.outputs.number }}
  #         github-token: ${{ secrets.GITHUB_TOKEN }}   # ← required
