name: CI 

on:
  push:
    branches:
      - main # only run on direct pushes to main
  pull_request:
    # run on all PRs

jobs: 
  tests: 
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v4 
      - name: Install Dependencies
        run: npm install
      - name: Unit Test
        run: npm run test  
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install modules
      run: npm install
    - name: Run ESLint
      run: npx eslint ./

  validate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate markup with Nu HTML Checker
        uses: Cyb3r-Jak 3/html5validator-action@v7.2.0   
        with:
          root: .               
          format: gnu        
          css: true  
          blacklist: "node_modules"

  jsdoc:
    - name: JSDoc Action
      uses: andstor/jsdoc-action@v1.2.1
